POST http://127.0.0.1:8000/accounts/api/permissions HTTP/1.1
content-type: application/json

{
"name" : "Org Head",
"permissions" : {
    "1" : {
        "context" : 1,
        "status" : true
        },
"2" : {
        "context" : 3,
        "status" : false
    }
}
}


###
PATCH http://127.0.0.1:8000/accounts/api/permissions/5 HTTP/1.1
Content-Type: application/json

{
    "name": "school heads",
    "permissions" : {
    "1" : {
        "context" : 1,
        "status" : false
        }
}
}
###
GET http://127.0.0.1:8000/accounts/api/get_group_permissions HTTP/1.1

