# Generated by Django 4.2.1 on 2023-05-25 12:16

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    groups = ['organisation','school','central_coordinator','school_coordinator','teacher','student','parent','training_team',]
    group_objects = [Group(name=grp_name) for grp_name in groups ]
    Group.objects.bulk_create(group_objects)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
