# Generated by Django 4.2.1 on 2023-07-10 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_messagetype_message_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='pincode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid pincode', regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone/mobile number', regex='^(\\+[1-9][0-9]*-)?[1-9][0-9]{6,}$')]),
        ),
    ]
