# Generated by Django 4.2.1 on 2023-06-06 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_city_remove_profile_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='district',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='state',
        ),
        migrations.RemoveField(
            model_name='school',
            name='city',
        ),
        migrations.RemoveField(
            model_name='school',
            name='district',
        ),
        migrations.RemoveField(
            model_name='school',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='school',
            name='state',
        ),
        migrations.AddField(
            model_name='organisation',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.location'),
            preserve_default=False,
        ),
    ]
