# Generated by Django 4.2.1 on 2023-06-07 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_organisation_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralcoordinator',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolcoordinator',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name_of_association',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name_of_association',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
