# Generated by Django 4.2.1 on 2023-06-14 08:21

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_centralcoordinator_profile_schoolcoordinator_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centralcoordinator',
            options={'ordering': ['first_name', 'last_name'],
                     'verbose_name': 'Central Coordinator',
                     'verbose_name_plural': 'Central Coordinators'},
        ),
        migrations.AlterModelOptions(
            name='classcoordinator',
            options={'ordering': ['teacher__first_name', 'teacher__last_name']},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='schoolcoordinator',
            options={'ordering': ['first_name', 'last_name'],
                     'verbose_name': 'School Coordinator',
                     'verbose_name_plural': 'School Coordinators'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='trainingteam',
            options={'ordering': ['first_name', 'last_name'],
                     'verbose_name': 'Training Team',
                     'verbose_name_plural': 'Training Team'},
        ),
        migrations.AlterModelManagers(
            name='centralcoordinator',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='parent',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='schoolcoordinator',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='teacher',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='trainingteam',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='centralcoordinator',
            name='id',
        ),
        migrations.RemoveField(
            model_name='centralcoordinator',
            name='user',
        ),
        # migrations.RemoveField(
        #     model_name='parent',
        #     name='id',
        # ), # FK dependency in student model
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='schoolcoordinator',
            name='id',
        ),
        migrations.RemoveField(
            model_name='schoolcoordinator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        # migrations.RemoveField(
        #     model_name='teacher',
        #     name='id',
        # ), # FK dependency in student model
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trainingteam',
            name='id',
        ),
        migrations.RemoveField(
            model_name='trainingteam',
            name='user',
        ),
        migrations.AddField(
            model_name='centralcoordinator',
            name='user_ptr',
            field=models.OneToOneField(default=1,
                                       on_delete=django.db.models.deletion.PROTECT,
                                       parent_link=True, primary_key=True,
                                       serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='user_ptr',
            field=models.OneToOneField(default=1,
                                       on_delete=django.db.models.deletion.PROTECT,
                                       parent_link=True, primary_key=False,
                                       serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolcoordinator',
            name='user_ptr',
            field=models.OneToOneField(default=1,
                                       on_delete=django.db.models.deletion.PROTECT,
                                       parent_link=True, primary_key=True,
                                       serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='_parent',
            field=models.ForeignKey(default=1,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    related_name='children', to='accounts.parent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='_teacher',
            field=models.ForeignKey(default=1,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    related_name='students', to='accounts.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1,
                                       on_delete=django.db.models.deletion.CASCADE,
                                       parent_link=True, primary_key=True,
                                       serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='user_ptr',
            field=models.OneToOneField(default=1,
                                       on_delete=django.db.models.deletion.PROTECT,
                                       parent_link=True, primary_key=False,
                                       serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingteam',
            name='user_ptr',
            field=models.OneToOneField(default=1,
                                       on_delete=django.db.models.deletion.PROTECT,
                                       parent_link=True, primary_key=True,
                                       serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1, max_length=20, validators=[
                django.core.validators.RegexValidator(
                    message='Enter a valid phone/mobile number',
                    regex='^\\+?[0-9]+-?[0-9]{6,}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centralcoordinator',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='associated_organisation',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='profile_info',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='school',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='school_added',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schoolcoordinator',
            name='profile',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='trainingteam',
            name='profile',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='accounts.profile'),
        ),
    ]
